# YuToDo Configuration File
# This is an example configuration file in TOML format
# Copy this file and customize it according to your preferences

[app]
  [app.window]
    # Keep the application window always on top
    always_on_top = false

    # Initial window dimensions
    width = 1024
    height = 768

    # Minimum window dimensions
    min_width = 400
    min_height = 300

  [app.ui]
    # Theme: "auto" (follow system), "light", or "dark"
    theme = "auto"

    # Show detailed view with descriptions, filters, etc.
    detailed_mode = false

    # Automatically hide header when window is not focused
    auto_hide_header = true

  [app.behavior]
    # Automatically save changes
    auto_save = true

    # Enable keyboard shortcuts
    enable_shortcuts = true

    # Show system notifications
    show_notifications = true

[server]
  # Server URL for todo synchronization
  url = "http://localhost:3001"

  # Connection timeout in milliseconds
  timeout = 5000

  # Number of retry attempts when connection fails
  retry_attempts = 3

[appearance]
  # Custom CSS styles (optional)
  custom_css = """
  .todo-item {
    border-radius: 8px;
  }

  .todo-item:hover {
    transform: translateY(-1px);
  }
  """

  # Font family (optional)
  font_family = "Inter, sans-serif"

  # Base font size in pixels
  font_size = 14

[shortcuts]
  # Keyboard shortcuts (optional)
  # Format: "Ctrl+Key", "Alt+Key", "Shift+Key", "Meta+Key", or "F1-F12"

  # Create new task
  new_task = "Ctrl+N"

  # Toggle settings panel
  toggle_settings = "Ctrl+,"

  # Focus search input
  focus_search = "Ctrl+F"

  # Select all tasks
  select_all = "Ctrl+A"

  # Delete selected tasks
  delete_selected = "Delete"

  # Show help
  show_help = "F1"
