apiVersion: v2
name: yutodo
description: A comprehensive Helm chart for YuToDo task management application with enterprise-grade features
type: application
version: 1.0.0
appVersion: "1.0.0"
home: https://github.com/your-org/yutodo
sources:
  - https://github.com/your-org/yutodo
maintainers:
  - name: YuToDo Team
    email: team@yutodo.dev
keywords:
  - todo
  - task-management
  - productivity
  - real-time
  - websocket
  - sqlite
  - tauri
annotations:
  category: Productivity
  licenses: MIT
dependencies:
  - name: postgresql
    version: 12.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 17.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: prometheus
    version: 15.x.x
    repository: https://prometheus-community.github.io/helm-charts
    condition: monitoring.prometheus.enabled
  - name: grafana
    version: 6.x.x
    repository: https://grafana.github.io/helm-charts
    condition: monitoring.grafana.enabled