apiVersion: v1
kind: Service
metadata:
  name: {{ include "yutodo.fullname" . }}
  namespace: {{ include "yutodo.namespace" . }}
  labels:
    {{- include "yutodo.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if eq .Values.service.type "NodePort" }}
  {{- if .Values.service.nodePort }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
      nodePort: {{ .Values.service.nodePort }}
  {{- end }}
  {{- else }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
    {{- if .Values.monitoring.enabled }}
    - port: 9090
      targetPort: metrics
      protocol: TCP
      name: metrics
    - port: 9100
      targetPort: node-metrics
      protocol: TCP
      name: node-metrics
    {{- end }}
  {{- end }}
  selector:
    {{- include "yutodo.selectorLabels" . | nindent 4 }}
  {{- if eq .Values.service.type "LoadBalancer" }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- range .Values.service.loadBalancerSourceRanges }}
    - {{ . }}
    {{- end }}
  {{- end }}
  {{- end }}

{{- if .Values.monitoring.enabled }}
---
# Headless service for direct pod access (monitoring)
apiVersion: v1
kind: Service
metadata:
  name: {{ include "yutodo.fullname" . }}-headless
  namespace: {{ include "yutodo.namespace" . }}
  labels:
    {{- include "yutodo.labels" . | nindent 4 }}
    service-type: headless
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
    - port: 9090
      targetPort: metrics
      protocol: TCP
      name: metrics
    - port: 9100
      targetPort: node-metrics
      protocol: TCP
      name: node-metrics
  selector:
    {{- include "yutodo.selectorLabels" . | nindent 4 }}
{{- end }}